### ISSUE TITLE
Namespace pollution: header hygiene

### ISSUE THREAD

**Issue by daniel-j-h** [fairlight1337/libcflie#7]
All your API headers pollute **my** namespace by

    using namespace std;

Please fix this in the API headers at least.
I do not want nor need the std namespace pollution.

**Comment by boaz001** [comment]
This patch should fix everything except for the gui example. Feel free to use it: https://github.com/boaz001/libcflie/commit/586d36dbee20d95b12388ca14f00ba5420f954c2

**Comment by fairlight1337** [comment]
Great, thanks! Looks good.
Some details were missing; I fixed them and the example files in 209c35aa9bf5861ca818c6b4ed168c9f5152b544.

Good job!
